import random
import string
import json

from lib.wrapper import fastql_server


params = {
    'prompt': ('String!', 'a text prompt for the image you want generated'),
    'artifact': ('String', 'blah'),
    'artifactType': ('String', 'blah'),
    'model': ('String', 'blah'),
}
fields = {
    'images': ('[String]', 'a collection of images generated by the model'),
    'tokens': ('[String]', 'blah')
}

params2 = {
    'prompt': {
        'type': 'String', 
        'description': 'a text prompt for the image you want generated'
    },
    'artifact': {
        'type': 'String'
    },
    'artifactType': {
        'type': 'String'
    },
    'model': {
        'type': 'String'
    },
}
def run_model(message):
    print("running model")
    # return f"{message} : {''.join(random.choice(string.digits) for i in range(10))}"
    return json.dumps({
        "images": "some stuff",
        "tokens": "an array of stuff"
    })

fastql_server.start(callback=run_model, params=params2, fields=fields)
