import random
import string
from lib.wrapper import fastql_server


params = {
    'prompt': ('String!', 'a text prompt for the image you want generated'),
    'artifact': ('String', 'blah'),
    'artifactType': ('String', 'blah'),
    'model': ('String', 'blah'),
}
fields = {
    'images': ('[String]', 'a collection of images generated by the model'),
    'tokens': ('[String]', 'blah')
}

def run_model(message):
    print("running model")
    return f"{message} : {''.join(random.choice(string.digits) for i in range(10))}"

fastql_server.start(callback=run_model, params=params, fields=fields)
